clankapp/home/views.py
from flask import Blueprint, render_template, session, url_for, redirect
from clankapp.models import db
home = Blueprint('home', __name__, template_folder='templates',static_folder='static', url_prefix='/')


@home.route('/')
def startpage():
    top_recipes = db.recipes.find({}).sort("upvotes", -1)
    new_recipes = db.recipes.find({}).sort("date_added", -1)
    
    return render_template('home.html', top_recipes = top_recipes, new_recipes = new_recipes)

@home.route('/alcoholic')
def alcoholic():
    top_recipes = db.recipes.find({'category':'Alcoholic'}).sort("upvotes", -1)
    new_recipes = db.recipes.find({'category':'Alcoholic'}).sort("date_added", -1)
    
    return render_template('alcoholic.html', top_recipes = top_recipes, new_recipes = new_recipes)

@home.route('/non-alcoholic')
def nonalcoholic():
    top_recipes = db.recipes.find({'category':'Non-alcoholic'}).sort("upvotes", -1)
    new_recipes = db.recipes.find({'category':'Non-alcoholic'}).sort("date_added", -1)
    
    return render_template('nonalcoholic.html', top_recipes = top_recipes, new_recipes = new_recipes)


@home.route('/clear')
def clear():
    session.clear()
    return redirect(url_for('home.startpage'))

clankapp/views/home.py
from flask import Blueprint, render_template, session, url_for, redirect, abort, send_from_directory, request
from clankapp.models import db
home = Blueprint('home', __name__, template_folder='templates',static_folder='static', url_prefix='/')
recipes = db['recipes']


@home.route('/')
def startpage():
    top_recipes = db.recipes.find({}).sort("upvotes", -1)
    new_recipes = db.recipes.find({}).sort("date_added", -1)
    
    return render_template('home/home.html', top_recipes = top_recipes, new_recipes = new_recipes)

@home.route('/alcoholic')
def alcoholic():
    top_recipes = db.recipes.find({'category':'Alcoholic'}).sort("upvotes", -1)
    new_recipes = db.recipes.find({'category':'Alcoholic'}).sort("date_added", -1)
    
    return render_template('home/alcoholic.html', top_recipes = top_recipes, new_recipes = new_recipes)

@home.route('/non-alcoholic')
def nonalcoholic():
    top_recipes = db.recipes.find({'category':'Non-alcoholic'}).sort("upvotes", -1)
    new_recipes = db.recipes.find({'category':'Non-alcoholic'}).sort("date_added", -1)
    
    return render_template('home/nonalcoholic.html', top_recipes = top_recipes, new_recipes = new_recipes)


@home.route('/clear')
def clear():
    session.clear()
    return redirect(url_for('home.startpage'))

@home.route('/search', methods=['GET','POST'])
def search():
    if request.method == 'POST':
        form = request.form
        search_term = form['search_string']
        if (search_term != ''):
            return render_template('home/search.html', all_recipes=recipes.find({'$text':{'$search': search_term}}))
        return render_template('home/search.html', message='Nothing Found')
    return render_template('home/search.html', message='Nothing Found')



@home.errorhandler(404)
def not_found(e):
    return "404", 404



@home.route('/sitemap.xml')
def sitemap():
    return send_from_directory('static', 'sitemap.xml')

@home.route('/robots.txt')
def robots():
    return send_from_directory('static', 'robots.txt')

clankapp/templates/home/alcoholic.html
{% extends 'home/homebase.html' %}

{% block title %} Alcoholic {% endblock %}


{% block body %} 


<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2 badge-color">Popular Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if top_recipes %}
{% for recipe in top_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>

<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2">New Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if new_recipes %}
{% for recipe in new_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>



<br />

  
{% endblock %}

clankapp/templates/home/home.html
{% extends 'home/homebase.html' %}

{% block title %} Home {% endblock %}


{% block body %} 
<div class="home-header">
<h1 class="text-center text-white pt-5">WikiBooze</h1>
<h2 class="text-center text-white pt-3">Recipes for your favorite beverages.</h2>
<p class="text-center pt-5"><a href="#anchor" class="text-white">Scroll Down to Explore</a></p>
</div>

<div class="container mt-5" id="anchor">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2 badge-color">Popular Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if top_recipes %}
{% for recipe in top_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p> 
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>

<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2">New Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if new_recipes %}
{% for recipe in new_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>



<br />


 




  



{% endblock %}

clankapp/templates/home/homebase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock%} | WikiBooze</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheet.css') }}">
    <meta name="description" 
content="Discover recipes for your taste buds. Explore countless recipes created by users just like you!">
<!-- Twitter Card data -->
<meta name="twitter:card" value="Discover recipes for your taste buds. Explore countless recipes created by users just like you!">

<!-- Open Graph data -->
<meta property="og:title" content="WikiBooze" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.wikibooze.com/" />
<meta property="og:image" content="{{url_for('static', filename='OldFashioned.png')}}" />
<meta property="og:description" content="Discover recipes for your taste buds. Explore countless recipes created by users just like you!" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XBBY2SBQG7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XBBY2SBQG7');
</script>

</head>
<body>
  <nav class="p-3 navbar navbar-expand-lg navbar-dark bg-dark text-white transhead">
    <div class="container">
      <a class="navbar-brand" href="/">WikiBooze</a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Recipes
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/alcoholic">Alcoholic</a></li>
              <li><a class="dropdown-item" href="/non-alcoholic">Non-Alcoholic</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/post-recipe">Post a Recipe</a></li>
            </ul>
          </li>

          
          
         
          
        </ul>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{{ url_for('home.search') }}" method="POST">
          <input type="search" name="search_string" class="form-control form-control-dark" placeholder="Search...">
          
        </form>
        
  {% if session.get('authenticated', False) == False %}
        <div class="text-end">
          <a href="/login" class="btn btn-light">login</a>
          <a href="/signup" class="btn btn-warning">sign-up</a>
        </div>
  {% else %}
        <div class="text-end">
          <a href="/logout" class="btn btn-light">logout</a>
        </div>
{% endif %}
      </div>
    </div>
  </nav>


    
      
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {%else%}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    
        
        
        {% block body %}

        {% endblock %}

   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

clankapp/templates/home/nonalcoholic.html
{% extends 'home/homebase.html' %}

{% block title %} Non-Alcoholic {% endblock %}


{% block body %} 


<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2 badge-color">Popular Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if top_recipes %}
{% for recipe in top_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>

<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2">New Recipes</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if new_recipes %}
{% for recipe in new_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% endif %}
  </div>
</div>



<br />

  
{% endblock %}

clankapp/templates/home/search.html
{% extends 'home/homebase.html' %}

{% block title %} Alcoholic {% endblock %}


{% block body %} 


<div class="container mt-5">
  <span class="badge bg-dark mb-3 p-2 fs-9 mx-2 badge-color">Search</span>
  <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto">
{% if all_recipes %}
{% for recipe in all_recipes %}
<div class="col">
  <div class="card cardhover" style="width: auto;">
    
    <div class="cardheader rounded-top">
      <p class="fs-4 fw-bold align-justify">{{recipe['recipe_name']}}</p>
      <p class="fs-6 fw-light align-justify p-0 m-0">{{recipe['category']}}</p>
      </div>
    {% if recipe['upvotes'] > 0 %}
      <span class="badge rounded-0 upvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% else %}
      <span class="badge rounded-0 downvote text-dark float-md-end fs-7 fw-light"><span class="fw-normal">{{recipe['upvotes']}}</span> upvotes</span>
      {% endif %}
    <div class="card-body min-height">
      
      <h5 class="card-title fs-6">Description</h5>
      
      <p class="card-text">{{recipe['description'][0:125]}}...</p>
      
      <a href="/recipe/{{recipe['_id']}}" class="btn btn-outline-secondary stretched-link">Visit Recipe</a>
    </div>
    <div class="card-footer d-flex justify-content-between py-1 px-2 fw-light fs-6">
      <small class="text-muted">Posted: {{recipe['date_added'].strftime('%Y-%m-%d')}}</small>
      <small class="text-muted">By: {{recipe['username']}}</small>
    </div>
  </div>
  


</div>


{% endfor %}
{% else %}

<h1>Nothing Found</h1>

{% endif %}

  </div>
</div>





  



<br />

  
{% endblock %}